version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:39:c0:28:fa:93:2c:ae:8b:68:c5:a0:46:f0:5c:0e"
      - checkout
      - run: git submodule sync
      # - run: git submodule update --init
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - miguel-blog-{{ checksum "stack.yaml" }}
            - miguel-blog-
      # - run:
      #     name: Prepare
      #     command: |
      #       git submodule init
      #       git submodule update
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Stack build
          command: stack --no-terminal build
      - run:
          name: Run tests
          command: stack --no-terminal test
      - run:
          name: Build site
          command: |
            stack --no-terminal exec site build
      - run:
          name: Publish
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            cd _site
            git add --all
            git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            git push origin master
      - save_cache:
          name: Cache Dependencies
          key: miguel-blog-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
general:
  branches:
    only:
     - hakyll
