flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- cmark-0.4.1
- conduit-extra-1.1.10.1
- hakyll-4.7.3.0
- highlighting-kate-0.6.1
- hslua-0.3.13
- pandoc-1.15.2.1
- primitive-0.6.1.0
- syb-0.4.4
- texmath-0.8.4.2
- time-locale-compat-0.1.0.1
- vector-0.11.0.0
- yaml-0.8.13
resolver: lts-3.2
