flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- cmark-0.6
- conduit-extra-1.3.6
- hslua-2.1.0
- pandoc-2.17.1.1
- primitive-0.7.3.0
- texmath-0.12.4
- vector-0.12.3.1
- yaml-0.11.8.0
resolver: lts-19.32
