name: build-and-publish-on-commit

run-name: Build and publish on commit ${{github.sha}}

on:
  push:
    branches:
      - hakyll

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.8.3']
        cabal: ['2.4.1.0']
        os: [ubuntu-latest]
        resolver: [lts-18]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8.3
            cabal: 2.4.1.0
    name: ${{ matrix.resolver }} (${{ matrix.ghc }}/${{ matrix.cabal }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
      - name: update module
        run: |
          git submodule sync
          git submodule update --remote
      - name: build
        run: |
          stack --resolver ${{ matrix.resolver }} build --no-run-tests --no-run-benchmarks
      - name: hakyll build
        run: |
          stack --no-terminal exec site build
